# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [19]:
planet = "Earth"
diameter = 12742
print("The diameter of {} if {} kilometers.".format(planet,diameter))

The diameter of Earth if 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [17]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [5]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [3]:
import numpy as np
a=[0,0,0,0,0,0,0,0,0,0]
arr=np.array(a)

In [4]:
import numpy as np
b=[5,5,5,5,5,5,5,5,5,5]
arrr=np.array(b)

## 5. Create an array of all the even integers from 20 to 35

In [5]:

s=[20,22,24,26,28,30,32,34]
even=np.array(s)
type(even)

numpy.ndarray

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [2]:
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [8]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
s=np.concatenate((a,b),axis=0)
print(s)


[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [27]:

import pandas as pd
students = [['ram', 34, 'washington', 'uk'],
			['jeevi', 30, 'Delhi', 'India'],
			['vinith', 31, 'Delhi', 'India'],]

dataframe = pd.DataFrame(students,
				columns=['Name', 'Age', 'City', 'Country'],
				index=['a', 'b', 'c'])

dataframe


Name  Age        City Country
a     ram   34  washington      uk
b   jeevi   30       Delhi   India
c  vinith   31       Delhi   India

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [10]:
import datetime
import pandas as pd


test_date = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")


K = 10

date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))


Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [15]:
# import pandas as pd
import pandas as pd
	
# List1
lists = [[1,'aaa', 22], [2,'bbb', 25],
	[3,'ccc',24]

# creating df object with columns specified	
data= pd.DataFrame(lists, columns)
print(df )


SyntaxError: ignored